name: build-mac

on:
  push:
    branches:
      - master

jobs:
  macos-latest:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Cache Homebrew
        uses: actions/cache@v3
        with:
          path: $(brew --prefix)
          key: ${{ runner.os }}-homebrew-${{ hashFiles('.config/brew/Brewfile') }}

      - name: Install Dependencies
        run: |
          brew update --preinstall
          brew install ninja

      - name: Build OpenCV
        run: ./deps.opencv/build-opencv-macos.zsh

      - name: Build FastDeploy
        run: ./deps.fastdeploy/build-fastdeploy-macos.zsh

      - name: Package Libraries
        run: |
          mkdir -p maa-deps-macos-universal/lib
          cp maa-deps-macos/lib/libopencv*.a maa-deps-macos-universal/lib
          cp maa-deps-macos/lib/libfastdeploy.0.0.0.dylib maa-deps-macos-universal/lib
          cp maa-deps-macos/*.cmake maa-deps-macos-universal
          find maa-deps-macos/third_libs/install -type f -name "*.dylib" '!' -path "*dSYM*" | xargs -I '{}' cp '{}' maa-deps-macos-universal/lib

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: maa-deps-macos-universal
          path: maa-deps-macos-universal
