name: build-mac

on:
  push:
    branches:
      - master

jobs:
  macos-latest:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Cache Homebrew
        uses: actions/cache@v3
        with:
          path: $(brew --prefix)
          key: ${{ runner.os }}-homebrew-${{ hashFiles('.config/brew/Brewfile') }}

      - name: Setup ccache
        uses: actions/cache@v3
        with:
          path: $HOME/Library/Cache/ccache
          key: ${{ runner.os }}-ccache-opencv4.6.0-fastdeploy-1.0.0
          restore-keys: ${{ runner.os }}-ccache-

      - name: Install Dependencies
        run: |
          brew update --preinstall
          brew install ccache ninja python

      - name: Build OpenCV
        run: ./deps.opencv/build-opencv-macos.zsh

      - name: Build Protobuf
        run: ./deps.protobuf/build-protobuf-macos.zsh

      - name: Build ONNXRuntime
        run: ./deps.onnxruntime/build-onnxruntime-macos.zsh

      - name: Build Paddle2ONNX
        run: ./deps.paddle2onnx/build-paddle2onnx-macos.zsh

      - name: Build FastDeploy
        run: ./deps.fastdeploy/build-fastdeploy-macos.zsh

      - name: Package Libraries
        run: tar Jcf maa-deps-macos.tar.xz maa-deps-macos

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: maa-deps-macos-universal
          path: maa-deps-macos.tar.xz