name: build-mac

on:
  push:
    branches:
      - master

jobs:
  macos-latest:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build OpenCV
        run: ./deps.opencv/build-opencv-macos.zsh
      - name: Build FastDeploy
        run: ./deps.fastdeploy/build-fastdeploy-macos.zsh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: maa-deps-macos
          path: maa-deps-macos
